name: Push Twilio environment variables

on:
  workflow_dispatch:

jobs:
  push_variables_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create and push environment file
        run: |
          echo "TWILIO_ACCOUNT_SID='ACc4f7b8e2ac4c15f6ba35d671cc8af7e7'" > twilio.env
          echo "TWILIO_AUTH_TOKEN='8f0500d3d531fcd5a0ee80ab31b21926'" >> twilio.env
          echo "twilio.env" >> .gitignore
          git add twilio.env
          git commit -m "Add Twilio environment variables"
          git push
